### ISSUE TITLE
Potential addition for functions without a return. 

### ISSUE THREAD

**Issue by Darkhax** [cpw/sidedtests#1]
Would it make sense to add an additional method for sided functions without a return type? In my tests this seems to work without having a nested supplier, and I think the majority of people using this system will not be making use of the supplied value. 

```java
    public static void run(Side side, Runnable toRun) {
        
        if (side == FMLCommonHandler.instance().getSide()) {
            
            try {
                
                toRun.run();
            }
            
            catch (Exception e) {

                throw new RuntimeException(e);
            }
        }
    }

**Comment by Niko-sk2x** [comment]
Except that this doesn't force it to be a runnable inside a runnable

**Comment by cpw** [comment]
The specifics of the SidedExecutor API are not the point of this repo. I agree there's quite a lot of useful ideas here, but lets' debate them where it matters. This repo is to prove a point about suppliers and classloading behaviour, and provide a common frame of reference for scenarios to test.
